# .streamlit/secrets.toml
data_key = "c0tnsrg914q_h9frg7GictyyTbM1cKsKB1LnGGCYwqVx"
OPENAI_API_KEY = "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"

[mysql]
host = "10.32.8.204"
port = 3306
database = "pdrb_tw"
user = "dev32net"
password = "BP5jab4rb3rk1bar"